In [2]:
import numpy as np
import pandas as pd

In [8]:
data = pd.read_csv('emails.csv')

In [9]:
data

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [11]:
data.shape

(5728, 2)

In [12]:
data.isnull().sum()

text    0
spam    0
dtype: int64

In [ ]:
# x and y

In [14]:
x = data.text.values

y = data.spam.values

In [ ]:
#split data

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [ ]:
#data preprocessing

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
vector=CountVectorizer()
x_train=vector.fit_transform(xtrain)

x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [4, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
#Machine learning algorithm

In [ ]:
#LinearRegression

In [22]:
from sklearn.linear_model import LinearRegression
lg=LinearRegression()

In [25]:
lg.fit(x_train,ytrain)

LinearRegression()

In [26]:
x_test=vector.transform(xtest)

In [32]:
result=lg.score(x_test,ytest)*100

In [35]:
result

3.330470679615205

In [73]:
emails = ['do not have money , get software cds .',' interest david , please , call..']

vector_emails = vector.transform(emails)

lg.predict(vector_emails)

array([0.34306337, 0.03679144])

In [74]:
#Naive-bayes

In [75]:
from sklearn.naive_bayes import MultinomialNB

In [76]:
model=MultinomialNB()

In [77]:
model.fit(x_train,ytrain)

MultinomialNB()

In [78]:
result=model.score(x_test,ytest)*100
result

99.12739965095986

In [79]:

model.predict(vector_emails)

array([1, 0], dtype=int64)

In [80]:
#randomforest

In [81]:
from sklearn.ensemble import RandomForestClassifier

In [82]:
clf= RandomForestClassifier()

In [83]:
clf.fit(x_train,ytrain)

RandomForestClassifier()

In [84]:
result=clf.score(x_test,ytest)*100
result

96.33507853403141

In [114]:
clf.predict(vector_emails1)

array([0, 0], dtype=int64)

In [115]:
#performance matrrix

In [135]:
pred = model.predict(x_test)

pred

array([1, 0, 0, ..., 0, 0, 1], dtype=int64)

In [136]:
#accuracy

In [137]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest,pred)

0.9912739965095986

In [138]:
from sklearn.metrics import confusion_matrix
confusion_matrix(ytest,pred)

array([[849,   5],
       [  5, 287]], dtype=int64)

In [140]:
#report

In [141]:
from sklearn.metrics import classification_report
print(classification_report(ytest,pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       854
           1       0.98      0.98      0.98       292

    accuracy                           0.99      1146
   macro avg       0.99      0.99      0.99      1146
weighted avg       0.99      0.99      0.99      1146

